### ISSUE TITLE
New issue with exporting to PDF. Possible Regression of Issue #

### ISSUE THREAD

**Issue by rjbprime** [jsnee/vscode-dmbinder#20]
Hi JSNee,

Started using the app again to update my campaign guide. Using current version of the plugin, and it now exports with an new(?) issue, that of the output pdf has a white page border on left and bottom sides of most pages, and the top and the left on the cover page.. Seems to be 2 to 3 mm on those two sides. I've tested my code in Homebrewery, and it doesn't show this error in that. 

I'm attaching the VSCode-DMBinder PDF and renamed md file to this post, and linking to the Homebrewery PDF Link as well. I know that the Homebrewery version Title page fonts are not the right size, but that's due to the code using for them. 

[Homebrewery version](https://homebrewery.naturalcrit.com/print/yK0OTIQ6m?dialog=true)

[manateros.pdf](https://github.com/jsnee/vscode-dmbinder/files/5237347/manateros.pdf)

[manateros.txt](https://github.com/jsnee/vscode-dmbinder/files/5237352/manateros.txt)

All A4 based.

**Comment by djfariel** [comment]
Heyyo! Adding a margin of 0px to the body seems to fix this.

```
<style>
  body{margin: 0px;}
</style>
```

**Comment by jsnee** [comment]
Sorted using custom styles
