### ISSUE TITLE
Needs support for installing to vscodium

### ISSUE THREAD

**Issue by buckleyc** [jsnee/vscode-dmbinder#25]
Request: Add extension to open-vsx.org for use with VSCodium.

Issue:
Using Visual Studio Code: DMBinder extension is found in extension marketplace.
Using VSCodium (https://vscodium.com): DMBinder extension is not found in default extension marketplace.

Currently:
I have both VSCode 1.55.0 and VSCodium 1.55.2 open. DMBinder is only available within the marketplace for VSCode.

Details:
The product.json file for VSCodium is set up to use open-vsx.org as extension gallery, versus VSCode's use of marketplace.visualstudio.com. (See https://github.com/VSCodium/vscodium/blob/master/DOCS.md#howto-vscode-marketplace)

Solution (recommended): 
Can this extension be added to open-vsx.org?
Alternate Solution:
Users would need to modify the settings to use the Microsoft Marketplace, which may not be legal. See above link for details.

**Comment by jsnee** [comment]
I'll look into it, if you're still interested

**Comment by buckleyc** [comment]
It would be nice, but do not put much time into this as there are noted workarounds (e.g., use VSCode). Thanks for looking into this.

**Comment by jsnee** [comment]
Has been published to open-vsx.org (Still waiting on my namespace claim to come through, though). You can find it at: https://open-vsx.org/extension/jpsnee/vscode-dmbinder
